const spells = [
  // ==========================
  //       CANTRIPS (0)
  // ==========================
  {
    name: "Acid Splash",
    class: "Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Target 1 or 2 creatures. DEX Save or take 1d6 acid damage."
  },
  {
    name: "Blade Ward",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "0",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "1 Round",
    effect: "Gain resistance to bludgeoning, piercing, and slashing from weapon attacks until end of next turn."
  },
  {
    name: "Chill Touch",
    class: "Sorcerer, Warlock, Wizard",
    level: "0",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "1 Round",
    effect: "Ranged Spell Attack: Deal 1d8 necrotic damage. Target cannot heal until your next turn."
  },
  {
    name: "Dancing Lights",
    class: "Bard, Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Create 4 faint lights. Bonus Action to move them up to 60 ft."
  },
  {
    name: "Druidcraft",
    class: "Druid",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Create tiny sensory effect, light/snuff candle, bloom seed, or predict weather."
  },
  {
    name: "Eldritch Blast",
    class: "Warlock",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Ranged Spell Attack: Deal 1d10 force damage. Beams increase to 2 (Lvl 5), 3 (Lvl 11), 4 (Lvl 17)."
  },
  {
    name: "Fire Bolt",
    class: "Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Ranged Spell Attack: Deal 1d10 fire damage. Ignites flammable objects."
  },
  {
    name: "Guidance",
    class: "Cleric, Druid, Artificer",
    level: "0",
    school: "Divination",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "Touch willing creature. Target adds 1d4 to one ability check of its choice."
  },
  {
    name: "Light",
    class: "Bard, Cleric, Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, M",
    duration: "1 Hour",
    effect: "Object touched sheds bright light (20 ft) and dim light (20 ft)."
  },
  {
    name: "Mage Hand",
    class: "Bard, Sorcerer, Warlock, Wizard, Artificer",
    level: "0",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "1 Minute",
    effect: "Create spectral hand to manipulate objects (5 lbs limit). Cannot attack or activate items."
  },
  {
    name: "Mending",
    class: "Bard, Cleric, Druid, Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Minute",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Repair a single break or tear in an object you touch."
  },
  {
    name: "Message",
    class: "Bard, Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "1 Round",
    effect: "Whisper message to creature. They hear you and can reply quietly."
  },
  {
    name: "Minor Illusion",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "0",
    school: "Illusion",
    castingTime: "1 Action",
    range: "30 ft",
    components: "S, M",
    duration: "1 Minute",
    effect: "Create a sound or static image (5ft cube). INT Save (Investigation) to detect."
  },
  {
    name: "Poison Spray",
    class: "Druid, Sorcerer, Warlock, Wizard, Artificer",
    level: "0",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "10 ft",
    components: "V, S",
    duration: "Instant",
    effect: "CON Save or take 1d12 poison damage."
  },
  {
    name: "Prestidigitation",
    class: "Bard, Sorcerer, Warlock, Wizard, Artificer",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "10 ft",
    components: "V, S",
    duration: "1 Hour",
    effect: "Minor tricks: sensory effect, light candle, clean item, flavor food, or small illusion."
  },
  {
    name: "Produce Flame",
    class: "Druid",
    level: "0",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "10 Minutes",
    effect: "Flame in hand provides light. Ranged Spell Attack to throw for 1d8 fire damage."
  },
  {
    name: "Ray of Frost",
    class: "Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Ranged Spell Attack: Deal 1d8 cold damage and reduce target speed by 10 ft."
  },
  {
    name: "Resistance",
    class: "Cleric, Druid, Artificer",
    level: "0",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Touch willing creature. Target adds 1d4 to one saving throw of its choice."
  },
  {
    name: "Sacred Flame",
    class: "Cleric",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "DEX Save or take 1d8 radiant damage. Ignores cover."
  },
  {
    name: "Shillelagh",
    class: "Druid",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Bonus Action",
    range: "Touch",
    components: "V, S, M",
    duration: "1 Minute",
    effect: "Imbue club/staff. Uses Spellcasting Stat for attack/damage. Deals 1d8 damage."
  },
  {
    name: "Shocking Grasp",
    class: "Sorcerer, Wizard, Artificer",
    level: "0",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    effect: "Melee Spell Attack: Deal 1d8 lightning damage. Target cannot take reactions."
  },
  {
    name: "Spare the Dying",
    class: "Cleric, Artificer",
    level: "0",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    effect: "Touch a living creature at 0 HP to stabilize them."
  },
  {
    name: "Thaumaturgy",
    class: "Cleric",
    level: "0",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V",
    duration: "1 Minute",
    effect: "Minor wonder: loud voice, flickering flames, tremors, sounds, or open unlocked doors."
  },
  {
    name: "True Strike",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "0",
    school: "Divination",
    castingTime: "1 Action",
    range: "30 ft",
    components: "S",
    duration: "Conc. (1 rnd)",
    effect: "Gain advantage on your next attack roll against target."
  },
  {
    name: "Vicious Mockery",
    class: "Bard",
    level: "0",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V",
    duration: "Instant",
    effect: "WIS Save or take 1d4 psychic damage and have disadvantage on next attack."
  },

  // ==========================
  //       LEVEL 1
  // ==========================
  {
    name: "Alarm",
    class: "Ranger, Wizard, Artificer",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Minute",
    range: "30 ft",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Wards an area. Triggers silent or audible alarm when creature enters."
  },
  {
    name: "Animal Friendship",
    class: "Bard, Druid, Ranger",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "24 Hours",
    effect: "WIS Save: Beast with INT < 4 is charmed by you."
  },
  {
    name: "Bane",
    class: "Bard, Cleric",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Up to 3 creatures. CHA Save: Subtract 1d4 from attacks and saves."
  },
  {
    name: "Bless",
    class: "Cleric, Paladin",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Up to 3 creatures. Add 1d4 to attack rolls and saving throws."
  },
  {
    name: "Burning Hands",
    class: "Sorcerer, Wizard",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (15 ft cone)",
    components: "V, S",
    duration: "Instant",
    effect: "15 ft Cone. DEX Save: Take 3d6 fire damage (half on success)."
  },
  {
    name: "Charm Person",
    class: "Bard, Druid, Sorcerer, Warlock, Wizard",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "1 Hour",
    effect: "WIS Save: Humanoid is charmed by you. Advantage on save if fighting."
  },
  {
    name: "Command",
    class: "Cleric, Paladin",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V",
    duration: "1 Round",
    effect: "WIS Save: Creature obeys a one-word command (e.g., Flee, Drop, Halt)."
  },
  {
    name: "Cure Wounds",
    class: "Bard, Cleric, Druid, Paladin, Ranger, Artificer",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    effect: "Touch a creature to heal them for 1d8 + Spellcasting Mod."
  },
  {
    name: "Detect Magic",
    class: "Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard, Artificer",
    level: "1",
    school: "Divination",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Sense presence of magic within 30 ft. Action to see auras and school."
  },
  {
    name: "Disguise Self",
    class: "Bard, Sorcerer, Wizard, Artificer",
    level: "1",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "1 Hour",
    effect: "Magically change your appearance, clothing, and belongings. Investigation check to discern."
  },
  {
    name: "Divine Favor",
    class: "Paladin",
    level: "1",
    school: "Evocation",
    castingTime: "1 Bonus Action",
    range: "Self",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "Your weapon attacks deal an extra 1d4 radiant damage on hit."
  },
  {
    name: "Entangle",
    class: "Druid",
    level: "1",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "20 ft square. STR Save: Restrained. Area becomes difficult terrain."
  },
  {
    name: "Faerie Fire",
    class: "Bard, Druid, Artificer",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V",
    duration: "Conc. (1 min)",
    effect: "20 ft cube. DEX Save. Objects/creatures outlined in light. Attacks have advantage."
  },
  {
    name: "Feather Fall",
    class: "Bard, Sorcerer, Wizard, Artificer",
    level: "1",
    school: "Transmutation",
    castingTime: "1 Reaction",
    range: "60 ft",
    components: "V, M",
    duration: "1 Minute",
    effect: "Up to 5 falling creatures descend slowly (60 ft/round) and take no falling damage."
  },
  {
    name: "Find Familiar",
    class: "Wizard",
    level: "1",
    school: "Conjuration",
    castingTime: "1 Hour",
    range: "10 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "Summon a spirit animal companion (e.g., owl, cat, toad)."
  },
  {
    name: "Fog Cloud",
    class: "Druid, Ranger, Sorcerer, Wizard",
    level: "1",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (1 hour)",
    effect: "Create 20 ft radius sphere of fog. Area is heavily obscured."
  },
  {
    name: "Goodberry",
    class: "Druid, Ranger",
    level: "1",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Create 10 berries. Each restores 1 HP and provides food for a day."
  },
  {
    name: "Grease",
    class: "Wizard, Artificer",
    level: "1",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "1 Minute",
    effect: "Cover 10 ft square in grease. DEX Save: Fall prone."
  },
  {
    name: "Guiding Bolt",
    class: "Cleric",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "1 Round",
    effect: "Ranged Spell Attack: Deal 4d6 radiant damage. Next attack against target has advantage."
  },
  {
    name: "Healing Word",
    class: "Bard, Cleric, Druid",
    level: "1",
    school: "Evocation",
    castingTime: "1 Bonus Action",
    range: "60 ft",
    components: "V",
    duration: "Instant",
    effect: "Heal a creature you see for 1d4 + Spellcasting Mod."
  },
  {
    name: "Hellish Rebuke",
    class: "Warlock",
    level: "1",
    school: "Evocation",
    castingTime: "1 Reaction",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Reaction to damage. DEX Save: Take 2d10 fire damage (half on success)."
  },
  {
    name: "Heroism",
    class: "Bard, Paladin",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "Target is immune to fear. Gains Temp HP equal to Spell Mod at start of each turn."
  },
  {
    name: "Hunter's Mark",
    class: "Ranger",
    level: "1",
    school: "Divination",
    castingTime: "1 Bonus Action",
    range: "90 ft",
    components: "V",
    duration: "Conc. (1 hour)",
    effect: "Mark creature. Deal +1d6 damage on hit. Advantage on tracking/perception."
  },
  {
    name: "Identify",
    class: "Bard, Wizard, Artificer",
    level: "1",
    school: "Divination",
    castingTime: "1 Minute",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Learn magical properties and spells affecting a touched object."
  },
  {
    name: "Inflict Wounds",
    class: "Cleric",
    level: "1",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    effect: "Melee Spell Attack: Deal 3d10 necrotic damage."
  },
  {
    name: "Mage Armor",
    class: "Sorcerer, Wizard",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Target willing unarmored creature. Base AC becomes 13 + Dexterity Mod."
  },
  {
    name: "Magic Missile",
    class: "Sorcerer, Wizard",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Create 3 darts that auto-hit. Deal 1d4 + 1 force damage each."
  },
  {
    name: "Protection from Evil and Good",
    class: "Cleric, Paladin, Warlock, Wizard",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Protect target against aberrations, celestials, fey, fiends, undead. Immunity to charm/fear."
  },
  {
    name: "Sanctuary",
    class: "Cleric, Artificer",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Bonus Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "1 Minute",
    effect: "Enemies must pass WIS Save to attack target. Ends if target attacks or casts spell."
  },
  {
    name: "Shield",
    class: "Sorcerer, Wizard",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Reaction",
    range: "Self",
    components: "V, S",
    duration: "1 Round",
    effect: "Gain +5 AC and immunity to Magic Missile until start of next turn."
  },
  {
    name: "Shield of Faith",
    class: "Cleric, Paladin",
    level: "1",
    school: "Abjuration",
    castingTime: "1 Bonus Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Target gains +2 bonus to AC."
  },
  {
    name: "Silent Image",
    class: "Bard, Sorcerer, Wizard",
    level: "1",
    school: "Illusion",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Create visual illusion (15 ft cube). No sound or smell. Investigation check to discern."
  },
  {
    name: "Sleep",
    class: "Bard, Sorcerer, Wizard",
    level: "1",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S, M",
    duration: "1 Minute",
    effect: "Roll 5d8. Put creatures to sleep (lowest current HP first) in 20 ft radius."
  },
  {
    name: "Thunderwave",
    class: "Bard, Druid, Sorcerer, Wizard",
    level: "1",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (15 ft cube)",
    components: "V, S",
    duration: "Instant",
    effect: "15 ft Cube. CON Save: Take 2d8 thunder damage and push 10 ft (half dmg on success)."
  },

  // ==========================
  //       LEVEL 2
  // ==========================
  {
    name: "Aid",
    class: "Artificer, Cleric, Paladin",
    level: "2",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Choose 3 creatures. Their Max HP and current HP increase by 5."
  },
  {
    name: "Barkskin",
    class: "Druid, Ranger",
    level: "2",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Target's AC cannot be less than 16."
  },
  {
    name: "Blindness/Deafness",
    class: "Bard, Cleric, Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V",
    duration: "1 Minute",
    effect: "CON Save: Target is blinded or deafened. Save repeats at end of turns."
  },
  {
    name: "Blur",
    class: "Artificer, Sorcerer, Wizard",
    level: "2",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Self",
    components: "V",
    duration: "Conc. (1 Minute)",
    effect: "Your body wavers. Attackers have disadvantage to hit you."
  },
  {
    name: "Darkness",
    class: "Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, M",
    duration: "Conc. (10 min)",
    effect: "Create 15 ft radius of magical darkness. Blocks darkvision. Light can't illuminate."
  },
  {
    name: "Enhance Ability",
    class: "Artificer, Bard, Cleric, Druid, Sorcerer",
    level: "2",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Grant advantage on checks for one stat (STR, DEX, CON, INT, WIS, CHA). Bear's Endurance gives 2d6 Temp HP."
  },
  {
    name: "Find Steed",
    class: "Paladin",
    level: "2",
    school: "Conjuration",
    castingTime: "10 Minutes",
    range: "30 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Summon a spirit steed (Warhorse, Pony, Elk, etc) that obeys your commands."
  },
  {
    name: "Flaming Sphere",
    class: "Druid, Sorcerer, Wizard",
    level: "2",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Create moving fire ball. DEX Save: 2d6 fire damage to nearby creatures."
  },
  {
    name: "Heat Metal",
    class: "Artificer, Bard, Druid",
    level: "2",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Target metal object glows red. 2d8 fire damage. CON Save or drop object."
  },
  {
    name: "Hold Person",
    class: "Bard, Cleric, Druid, Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: Humanoid is paralyzed. Save repeats at end of turns."
  },
  {
    name: "Invisibility",
    class: "Artificer, Bard, Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Target becomes invisible. Ends if they attack or cast a spell."
  },
  {
    name: "Lesser Restoration",
    class: "Artificer, Bard, Cleric, Druid, Paladin, Ranger",
    level: "2",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Instant",
    effect: "Cure one disease or condition: blinded, deafened, paralyzed, or poisoned."
  },
  {
    name: "Misty Step",
    class: "Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Conjuration",
    castingTime: "1 Bonus Action",
    range: "Self",
    components: "V",
    duration: "Instant",
    effect: "Teleport 30 ft to an unoccupied space you can see."
  },
  {
    name: "Moonbeam",
    class: "Druid",
    level: "2",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "5 ft radius beam. CON Save: Take 2d10 radiant damage (half on success)."
  },
  {
    name: "Pass Without Trace",
    class: "Druid, Ranger",
    level: "2",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Group gains +10 Stealth checks. Cannot be tracked magically."
  },
  {
    name: "Scorching Ray",
    class: "Sorcerer, Wizard",
    level: "2",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Make 3 Ranged Spell Attacks. Deal 2d6 fire damage per hit."
  },
  {
    name: "Shatter",
    class: "Artificer, Bard, Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "10 ft Radius. CON Save: Take 3d8 thunder damage (half on success)."
  },
  {
    name: "Spike Growth",
    class: "Druid, Ranger",
    level: "2",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "20 ft radius difficult terrain. Take 2d4 piercing damage for every 5 ft moved."
  },
  {
    name: "Spiritual Weapon",
    class: "Cleric",
    level: "2",
    school: "Evocation",
    castingTime: "1 Bonus Action",
    range: "60 ft",
    components: "V, S",
    duration: "1 Minute",
    effect: "Create floating weapon. Bonus Action to hit for 1d8 + Mod force damage."
  },
  {
    name: "Suggestion",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "2",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, M",
    duration: "Conc. (8 Hours)",
    effect: "WIS Save: Creature follows a reasonable suggested course of action."
  },
  {
    name: "Web",
    class: "Artificer, Sorcerer, Wizard",
    level: "2",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "20 ft cube of sticky webs. DEX Save: Restrained. Area is difficult terrain."
  },
  {
    name: "Zone of Truth",
    class: "Bard, Cleric, Paladin",
    level: "2",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "10 Minutes",
    effect: "15 ft Radius. CHA Save. On fail, creature cannot tell a deliberate lie."
  },

  // ==========================
  //       LEVEL 3
  // ==========================
  {
    name: "Call Lightning",
    class: "Druid",
    level: "3",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Create storm cloud. Action to call down bolt. DEX Save: 3d10 lightning damage."
  },
  {
    name: "Counterspell",
    class: "Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Abjuration",
    castingTime: "1 Reaction",
    range: "60 ft",
    components: "S",
    duration: "Instant",
    effect: "Interrupt spell. Auto-fail if Level 3 or lower. Ability Check for higher."
  },
  {
    name: "Dispel Magic",
    class: "Artificer, Bard, Cleric, Druid, Paladin, Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Instant",
    effect: "End spells on target. Auto-end Level 3 or lower. Ability Check for higher."
  },
  {
    name: "Fear",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Self (30 ft cone)",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "WIS Save: Drop items, become Frightened, and must dash away."
  },
  {
    name: "Fireball",
    class: "Sorcerer, Wizard",
    level: "3",
    school: "Evocation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "20 ft Radius Sphere. DEX Save: Take 8d6 fire damage (half on success)."
  },
  {
    name: "Fly",
    class: "Artificer, Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Touch willing creature. Target gains 60 ft flying speed."
  },
  {
    name: "Haste",
    class: "Artificer, Sorcerer, Wizard",
    level: "3",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Target gains +2 AC, double speed, Adv on DEX Saves, and one extra action. Lethargy when ends."
  },
  {
    name: "Hypnotic Pattern",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Illusion",
    castingTime: "1 Action",
    range: "120 ft",
    components: "S, M",
    duration: "Conc. (1 min)",
    effect: "30 ft Cube. WIS Save: Creatures are Charmed and Incapacitated. Speed 0."
  },
  {
    name: "Leomund's Tiny Hut",
    class: "Bard, Wizard",
    level: "3",
    school: "Evocation",
    castingTime: "1 Minute",
    range: "Self",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Create 10 ft dome of force. Impassable to enemies/spells. Safe rest."
  },
  {
    name: "Lightning Bolt",
    class: "Sorcerer, Wizard",
    level: "3",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (100 ft line)",
    components: "V, S, M",
    duration: "Instant",
    effect: "100 ft Line. DEX Save: Take 8d6 lightning damage (half on success)."
  },
  {
    name: "Major Image",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "3",
    school: "Illusion",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Create visual/auditory/olfactory illusion (20 ft cube). Investigation check to discern."
  },
  {
    name: "Mass Healing Word",
    class: "Cleric",
    level: "3",
    school: "Evocation",
    castingTime: "1 Bonus Action",
    range: "60 ft",
    components: "V",
    duration: "Instant",
    effect: "Heal up to 6 creatures for 1d4 + Spellcasting Mod."
  },
  {
    name: "Revivify",
    class: "Artificer, Cleric, Paladin, Ranger",
    level: "3",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Return creature to life with 1 HP if it died within the last minute."
  },
  {
    name: "Slow",
    class: "Bard, Sorcerer, Wizard",
    level: "3",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "WIS Save: Up to 6 targets. Speed halved, -2 AC, no reactions, limited actions."
  },
  {
    name: "Spirit Guardians",
    class: "Cleric",
    level: "3",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Self (15 ft)",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "15 ft Radius. WIS Save: 3d8 radiant/necrotic damage. Enemies speed halved."
  },
  {
    name: "Stinking Cloud",
    class: "Bard, Sorcerer, Wizard",
    level: "3",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "20 ft Radius Gas. CON Save: Spend action retching and reeling."
  },
  {
    name: "Vampiric Touch",
    class: "Warlock, Wizard",
    level: "3",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "Melee Spell Attack: Deal 3d6 necrotic damage. Heal for half damage dealt."
  },
  {
    name: "Water Breathing",
    class: "Artificer, Druid, Ranger, Sorcerer, Wizard",
    level: "3",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "24 Hours",
    effect: "Up to 10 willing creatures can breathe underwater."
  },
  // ==========================
  //       LEVEL 4
  // ==========================
  {
    name: "Arcane Eye",
    class: "Artificer, Wizard",
    level: "4",
    school: "Divination",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Create invisible eye. Mental commands to move it 30 ft. You see through it."
  },
  {
    name: "Banishment",
    class: "Cleric, Paladin, Sorcerer, Warlock, Wizard",
    level: "4",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "CHA Save: Target is banished to a harmless demiplane (or home plane). Incapacitated."
  },
  {
    name: "Blight",
    class: "Druid, Sorcerer, Warlock, Wizard",
    level: "4",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "Instant",
    effect: "CON Save: Take 8d8 necrotic damage (half on success). Max damage to plants."
  },
  {
    name: "Confusion",
    class: "Bard, Druid, Sorcerer, Wizard",
    level: "4",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "10 ft Radius. WIS Save: Creatures act randomly (roll d10) each turn. Save repeats end of turns."
  },
  {
    name: "Control Water",
    class: "Cleric, Druid, Wizard",
    level: "4",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "300 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Control water in 100 ft cube: Flood, Part Water, Redirect Flow, or Whirlpool."
  },
  {
    name: "Death Ward",
    class: "Cleric, Paladin",
    level: "4",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "8 Hours",
    effect: "Target drops to 1 HP instead of 0 HP the first time it would drop to 0. Negates instant death effects."
  },
  {
    name: "Dimension Door",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "4",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "500 ft",
    components: "V",
    duration: "Instant",
    effect: "Teleport yourself and one willing creature to a spot within range. No sight required."
  },
  {
    name: "Dominate Beast",
    class: "Druid, Sorcerer",
    level: "4",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: You telepathically control a beast. It obeys your commands. Save repeats when it takes damage."
  },
  {
    name: "Evard's Black Tentacles",
    class: "Wizard",
    level: "4",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "20 ft square difficult terrain. DEX Save or Restrained + 3d6 bludgeoning dmg. Turn start: 3d6 dmg to restrained."
  },
  {
    name: "Fire Shield",
    class: "Wizard",
    level: "4",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "10 Minutes",
    effect: "Thin flames surround you. Resistance to Cold or Fire. Melee attackers take 2d8 fire or cold damage."
  },
  {
    name: "Freedom of Movement",
    class: "Artificer, Bard, Cleric, Druid, Ranger",
    level: "4",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "1 Hour",
    effect: "Target ignores difficult terrain, paralysis, and restraints. Can swim/move underwater normally."
  },
  {
    name: "Giant Insect",
    class: "Druid",
    level: "4",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Transform nearby normal insects into giant versions (Spider, Centipede, Wasp, etc) that obey you."
  },
  {
    name: "Greater Invisibility",
    class: "Bard, Sorcerer, Wizard",
    level: "4",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "Target becomes invisible. Does NOT end if they attack or cast spells."
  },
  {
    name: "Guardian of Faith",
    class: "Cleric",
    level: "4",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V",
    duration: "8 Hours",
    effect: "Summon spectral guardian. Enemies within 10 ft must DEX Save: Take 20 radiant damage (10 on success). Vanishes after 60 dmg."
  },
  {
    name: "Ice Storm",
    class: "Druid, Sorcerer, Wizard",
    level: "4",
    school: "Evocation",
    castingTime: "1 Action",
    range: "300 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "20 ft Cylinder. DEX Save: Take 2d8 bludgeoning + 4d6 cold damage (half on success). Difficult terrain."
  },
  {
    name: "Locate Creature",
    class: "Bard, Cleric, Druid, Paladin, Ranger, Wizard",
    level: "4",
    school: "Divination",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Sense direction to specific creature or nearest creature of a kind within 1000 ft."
  },
  {
    name: "Otiluke's Resilient Sphere",
    class: "Artificer, Wizard",
    level: "4",
    school: "Evocation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "DEX Save: Enclose creature in impenetrable sphere. Nothing passes in or out. Target can roll the sphere."
  },
  {
    name: "Phantasmal Killer",
    class: "Wizard",
    level: "4",
    school: "Illusion",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: Target is Frightened. End of turns: 4d10 psychic damage if save fails again."
  },
  {
    name: "Polymorph",
    class: "Bard, Druid, Sorcerer, Wizard",
    level: "4",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "WIS Save: Transform creature into a beast of CR equal/less than target. It assumes beast's stats."
  },
  {
    name: "Stone Shape",
    class: "Artificer, Cleric, Druid, Wizard",
    level: "4",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Reshape stone object (medium size). Create doors, walls, or crude shapes."
  },
  {
    name: "Stoneskin",
    class: "Artificer, Bard, Druid, Ranger, Sorcerer, Wizard",
    level: "4",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Target gains resistance to nonmagical bludgeoning, piercing, and slashing damage. Consumes 100gp diamond dust."
  },
  {
    name: "Wall of Fire",
    class: "Druid, Sorcerer, Wizard, Artificer",
    level: "4",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Create wall/ring of fire. Passing through or ending turn near: DEX Save for 5d8 fire damage (half on success)."
  },
  // ==========================
  //       LEVEL 5
  // ==========================
  {
    name: "Animate Objects",
    class: "Bard, Sorcerer, Wizard, Artificer",
    level: "5",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "Animate up to 10 nonmagical objects. They become creatures that obey your bonus action commands."
  },
  {
    name: "Antilife Shell",
    class: "Druid",
    level: "5",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self (10 ft radius)",
    components: "V, S",
    duration: "Conc. (1 Hour)",
    effect: "10 ft radius barrier blocks living creatures from entering."
  },
  {
    name: "Awaken",
    class: "Bard, Druid",
    level: "5",
    school: "Transmutation",
    castingTime: "8 Hours",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Grant consciousness to beast or plant (INT 10). It is charmed by you for 30 days."
  },
  {
    name: "Bigby's Hand",
    class: "Wizard, Artificer",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Create Large hand. Bonus Action to punch (4d8 force), push, grasp (STR check), or interpose (cover)."
  },
  {
    name: "Cloudkill",
    class: "Sorcerer, Wizard",
    level: "5",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "20 ft Radius Fog. Moves 10 ft away/turn. CON Save: Take 5d8 poison damage (half on success)."
  },
  {
    name: "Commune",
    class: "Cleric, Paladin",
    level: "5",
    school: "Divination",
    castingTime: "1 Minute",
    range: "Self",
    components: "V, S, M",
    duration: "1 Minute",
    effect: "Ask deity 3 yes/no questions."
  },
  {
    name: "Cone of Cold",
    class: "Druid, Sorcerer, Wizard, Artificer",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (60 ft cone)",
    components: "V, S, M",
    duration: "Instant",
    effect: "60 ft Cone. CON Save: Take 8d8 cold damage (half on success)."
  },
  {
    name: "Conjure Elemental",
    class: "Druid, Wizard",
    level: "5",
    school: "Conjuration",
    castingTime: "1 Minute",
    range: "90 ft",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Summon CR 5 Elemental. It obeys verbal commands. Turns hostile if concentration breaks."
  },
  {
    name: "Contact Other Plane",
    class: "Warlock, Wizard",
    level: "5",
    school: "Divination",
    castingTime: "1 Minute",
    range: "Self",
    components: "V",
    duration: "1 Minute",
    effect: "Ask entity 5 questions. INT Save (DC 15) or take 6d6 psychic damage and become insane."
  },
  {
    name: "Contagion",
    class: "Cleric, Druid",
    level: "5",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "7 Days",
    effect: "Melee Spell Attack: Target poisoned. If fails 3 CON Saves, blinded/paralyzed/stunned by disease."
  },
  {
    name: "Creation",
    class: "Artificer, Sorcerer, Wizard",
    level: "5",
    school: "Illusion",
    castingTime: "1 Minute",
    range: "30 ft",
    components: "V, S, M",
    duration: "Special",
    effect: "Create nonliving object of vegetable (1 day), stone (12 hrs), or metal (1 hr) matter."
  },
  {
    name: "Dispel Evil and Good",
    class: "Cleric, Paladin",
    level: "5",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Disadvantage on attacks from celestials, elementals, fey, fiends, undead. Can break charms/possession or banish them."
  },
  {
    name: "Dominate Person",
    class: "Bard, Sorcerer, Wizard",
    level: "5",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: Telepathically control humanoid. Takes total control action."
  },
  {
    name: "Dream",
    class: "Bard, Warlock, Wizard",
    level: "5",
    school: "Illusion",
    castingTime: "1 Minute",
    range: "Special",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Shape target's dreams. Can converse or cause nightmare (3d6 psychic dmg, no long rest benefit)."
  },
  {
    name: "Flame Strike",
    class: "Cleric",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "10 ft Radius Column. DEX Save: Take 4d6 fire + 4d6 radiant damage (half on success)."
  },
  {
    name: "Geas",
    class: "Bard, Cleric, Druid, Paladin, Wizard",
    level: "5",
    school: "Enchantment",
    castingTime: "1 Minute",
    range: "60 ft",
    components: "V",
    duration: "30 Days",
    effect: "WIS Save: Command creature to do/avoid service. 5d10 psychic dmg if disobeyed daily."
  },
  {
    name: "Greater Restoration",
    class: "Artificer, Bard, Cleric, Druid",
    level: "5",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "End charm/petrify, remove curse, fix ability reduction, or max HP reduction."
  },
  {
    name: "Hallow",
    class: "Cleric",
    level: "5",
    school: "Evocation",
    castingTime: "24 Hours",
    range: "Touch",
    components: "V, S, M",
    duration: "Until Dispelled",
    effect: "Ward area (60 ft radius). Block specific creature types. Grant effects (Fear, Resistance, etc)."
  },
  {
    name: "Hold Monster",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "5",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: Creature is paralyzed. Save repeats at end of turns."
  },
  {
    name: "Insect Plague",
    class: "Cleric, Druid, Sorcerer",
    level: "5",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "300 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "20 ft Radius Sphere of locusts. Difficult terrain. CON Save: Take 4d10 piercing damage (half on success)."
  },
  {
    name: "Legend Lore",
    class: "Bard, Cleric, Wizard",
    level: "5",
    school: "Divination",
    castingTime: "10 Minutes",
    range: "Self",
    components: "V, S, M",
    duration: "Instant",
    effect: "Reveal lore about a person, place, or object of legendary importance."
  },
  {
    name: "Mass Cure Wounds",
    class: "Bard, Cleric, Druid",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Heal up to 6 creatures in 30 ft point. Restore 3d8 + Spell Mod HP."
  },
  {
    name: "Mislead",
    class: "Bard, Wizard",
    level: "5",
    school: "Illusion",
    castingTime: "1 Action",
    range: "Self",
    components: "S",
    duration: "Conc. (1 Hour)",
    effect: "Become invisible and create illusory double. You see/hear through double."
  },
  {
    name: "Modify Memory",
    class: "Bard, Wizard",
    level: "5",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "WIS Save: Charm target and rewrite 10 minutes of its memory."
  },
  {
    name: "Passwall",
    class: "Wizard",
    level: "5",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "1 Hour",
    effect: "Create 5x8 ft passage through wood, plaster, or stone wall (up to 20 ft deep)."
  },
  {
    name: "Planar Binding",
    class: "Bard, Cleric, Druid, Wizard",
    level: "5",
    school: "Abjuration",
    castingTime: "1 Hour",
    range: "60 ft",
    components: "V, S, M",
    duration: "24 Hours",
    effect: "CHA Save: Bind celestial, elemental, fey, or fiend to serve you."
  },
  {
    name: "Raise Dead",
    class: "Bard, Cleric, Paladin",
    level: "5",
    school: "Necromancy",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Return dead creature (within 10 days) to life with 1 HP. Cures non-magical diseases/poisons."
  },
  {
    name: "Reincarnate",
    class: "Druid",
    level: "5",
    school: "Transmutation",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Create new body for dead creature (within 10 days). Race is random."
  },
  {
    name: "Scrying",
    class: "Bard, Cleric, Druid, Warlock, Wizard",
    level: "5",
    school: "Divination",
    castingTime: "10 Minutes",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "WIS Save: Spy on a creature or location. Modifier based on connection/knowledge."
  },
  {
    name: "Seeming",
    class: "Bard, Sorcerer, Wizard",
    level: "5",
    school: "Illusion",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S",
    duration: "8 Hours",
    effect: "Change appearance of any number of creatures. CHA Save to resist."
  },
  {
    name: "Telekinesis",
    class: "Sorcerer, Wizard",
    level: "5",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Move creature (STR contest) or object (1000 lbs) with mind."
  },
  {
    name: "Teleportation Circle",
    class: "Bard, Sorcerer, Wizard",
    level: "5",
    school: "Conjuration",
    castingTime: "1 Minute",
    range: "10 ft",
    components: "V, M",
    duration: "1 Round",
    effect: "Create portal to a permanent teleportation circle you know."
  },
  {
    name: "Tree Stride",
    class: "Druid, Ranger",
    level: "5",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "Step into tree and exit another of same kind within 500 ft."
  },
  {
    name: "Wall of Force",
    class: "Wizard",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Create invisible, indestructible wall. Nothing can pass through."
  },
  {
    name: "Wall of Stone",
    class: "Druid, Sorcerer, Wizard",
    level: "5",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "Create wall of solid stone (6 inches thick). Becomes permanent if concentrated full duration."
  },
  // ==========================
  //       LEVEL 6
  // ==========================
  {
    name: "Arcane Gate",
    class: "Sorcerer, Warlock, Wizard",
    level: "6",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "500 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Create two linked portals. Creatures can move between them instantly."
  },
  {
    name: "Blade Barrier",
    class: "Cleric",
    level: "6",
    school: "Evocation",
    castingTime: "1 Action",
    range: "90 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Wall of spinning blades. 3/4 cover. DEX Save: Take 6d10 slashing damage."
  },
  {
    name: "Chain Lightning",
    class: "Sorcerer, Wizard",
    level: "6",
    school: "Evocation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "Target + 3 nearby enemies. DEX Save: Take 10d8 lightning damage (half on success)."
  },
  {
    name: "Circle of Death",
    class: "Sorcerer, Warlock, Wizard",
    level: "6",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "60 ft Radius Sphere. CON Save: Take 8d6 necrotic damage (half on success)."
  },
  {
    name: "Disintegrate",
    class: "Sorcerer, Wizard",
    level: "6",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "DEX Save: Take 10d6 + 40 force damage. If reduced to 0 HP, target turns to dust."
  },
  {
    name: "Eyebite",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "6",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "Glare at creature each turn. WIS Save: Asleep, Panicked, or Sickened."
  },
  {
    name: "Flesh to Stone",
    class: "Warlock, Wizard",
    level: "6",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "CON Save: Target is restrained, then petrified (turned to stone) if it fails 3 saves."
  },
  {
    name: "Globe of Invulnerability",
    class: "Sorcerer, Wizard",
    level: "6",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self (10 ft radius)",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Barrier blocks all spells of Level 5 or lower."
  },
  {
    name: "Guards and Wards",
    class: "Bard, Wizard",
    level: "6",
    school: "Abjuration",
    castingTime: "10 Minutes",
    range: "Touch",
    components: "V, S, M",
    duration: "24 Hours",
    effect: "Ward a stronghold (2500 sq ft). Adds locks, fog, webs, and confusion effects."
  },
  {
    name: "Harm",
    class: "Cleric",
    level: "6",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "CON Save: Take 14d6 necrotic damage. Max HP reduced by damage amount."
  },
  {
    name: "Heal",
    class: "Cleric, Druid",
    level: "6",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Target regains 70 HP. Ends blindness, deafness, and all diseases."
  },
  {
    name: "Heroes' Feast",
    class: "Cleric, Druid",
    level: "6",
    school: "Conjuration",
    castingTime: "10 Minutes",
    range: "30 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "Feast for 12. Cures disease, immune to poison/fear, Adv on WIS Saves, +2d10 Max HP."
  },
  {
    name: "Mass Suggestion",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "6",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, M",
    duration: "24 Hours",
    effect: "WIS Save: Up to 12 creatures follow a suggested course of action (no concentration)."
  },
  {
    name: "Move Earth",
    class: "Druid, Sorcerer, Wizard",
    level: "6",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (2 hours)",
    effect: "Reshape terrain. Create trenches, hills, or flatten 40 ft area."
  },
  {
    name: "Otto's Irresistible Dance",
    class: "Bard, Wizard",
    level: "6",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V",
    duration: "Conc. (1 min)",
    effect: "WIS Save: Target dances. Speed 0, disadvantage on attacks/dex saves. Attacks against it have advantage."
  },
  {
    name: "Planar Ally",
    class: "Cleric",
    level: "6",
    school: "Conjuration",
    castingTime: "10 Minutes",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Beseech entity for aid. Summon celestial, elemental, or fiend to perform service (payment required)."
  },
  {
    name: "Sunbeam",
    class: "Druid, Sorcerer, Wizard",
    level: "6",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (60 ft line)",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Create beam each turn. CON Save: 6d8 radiant damage + blinded."
  },
  {
    name: "Transport via Plants",
    class: "Druid",
    level: "6",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "1 Round",
    effect: "Step into one plant and exit another of the same kind any distance away."
  },
  {
    name: "True Seeing",
    class: "Bard, Cleric, Sorcerer, Warlock, Wizard",
    level: "6",
    school: "Divination",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "1 Hour",
    effect: "Touch willing creature. Grants Truesight 120 ft (see invisible, illusions, Ethereal Plane)."
  },
  {
    name: "Wall of Ice",
    class: "Wizard",
    level: "6",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S, M",
    duration: "Conc. (10 min)",
    effect: "DEX Save: 10d6 cold damage. Creates solid ice wall (AC 12, 30 HP per section)."
  },
  {
    name: "Wind Walk",
    class: "Druid",
    level: "6",
    school: "Transmutation",
    castingTime: "1 Minute",
    range: "30 ft",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "You and 10 allies turn into gaseous clouds. Fly speed 300 ft. Resistance to non-magical damage."
  },
  {
    name: "Word of Recall",
    class: "Cleric",
    level: "6",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "5 ft",
    components: "V",
    duration: "Instant",
    effect: "Teleport yourself and 5 willing creatures to a designated sanctuary."
  },

  // ==========================
  //       LEVEL 7
  // ==========================
  {
    name: "Arcane Sword",
    class: "Bard, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Create floating sword. Action to attack: 3d10 force damage."
  },
  {
    name: "Conjure Celestial",
    class: "Cleric",
    level: "7",
    school: "Conjuration",
    castingTime: "1 Minute",
    range: "90 ft",
    components: "V, S",
    duration: "Conc. (1 hour)",
    effect: "Summon Celestial (CR 4 or lower). It obeys your commands."
  },
  {
    name: "Delayed Blast Fireball",
    class: "Sorcerer, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Bead explodes when duration ends. DEX Save: 12d6 fire damage (+1d6 per turn delayed)."
  },
  {
    name: "Divine Word",
    class: "Cleric",
    level: "7",
    school: "Evocation",
    castingTime: "1 Bonus Action",
    range: "30 ft",
    components: "V",
    duration: "Instant",
    effect: "CHA Save: Enemies suffer effect based on current HP. <20 HP: Instant Death."
  },
  {
    name: "Etherealness",
    class: "Bard, Cleric, Sorcerer, Warlock, Wizard",
    level: "7",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S",
    duration: "8 Hours",
    effect: "Step into Ethereal Plane. Move through objects. Invisible to Material Plane."
  },
  {
    name: "Finger of Death",
    class: "Sorcerer, Warlock, Wizard",
    level: "7",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "CON Save: Take 7d8 + 30 necrotic damage. Humanoid killed rises as Zombie under your control."
  },
  {
    name: "Fire Storm",
    class: "Cleric, Druid, Sorcerer",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Create 10 connected 10ft cubes of fire. DEX Save: Take 7d10 fire damage."
  },
  {
    name: "Forcecage",
    class: "Bard, Warlock, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "100 ft",
    components: "V, S, M",
    duration: "1 Hour",
    effect: "Trap creature in 20ft cage or 10ft box of force. No save. Blocks spells/travel out."
  },
  {
    name: "Mirage Arcane",
    class: "Bard, Druid, Wizard",
    level: "7",
    school: "Illusion",
    castingTime: "10 Minutes",
    range: "Sight",
    components: "V, S, M",
    duration: "10 Days",
    effect: "Alter terrain/structures in 1 mile sq. Illusion is tactile and interacts physically."
  },
  {
    name: "Mordenkainen's Sword",
    class: "Bard, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "Floating sword makes melee spell attacks. 3d10 force damage."
  },
  {
    name: "Plane Shift",
    class: "Cleric, Druid, Sorcerer, Warlock, Wizard",
    level: "7",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Teleport group to another plane. OR Touch Attack: CHA Save to banish enemy."
  },
  {
    name: "Prismatic Spray",
    class: "Sorcerer, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (60 ft cone)",
    components: "V, S",
    duration: "Instant",
    effect: "8 rays with random effects (Fire, Acid, Lightning, Petrification, Banishment). DEX Save usually."
  },
  {
    name: "Project Image",
    class: "Bard, Wizard",
    level: "7",
    school: "Illusion",
    castingTime: "1 Action",
    range: "500 Miles",
    components: "V, S, M",
    duration: "Conc. (1 Day)",
    effect: "Create illusory copy of self. You can see/hear/speak through it."
  },
  {
    name: "Regenerate",
    class: "Bard, Cleric, Druid",
    level: "7",
    school: "Transmutation",
    castingTime: "1 Minute",
    range: "Touch",
    components: "V, S, M",
    duration: "1 Hour",
    effect: "Target regains 4d8 + 15 HP. Regains 1 HP per turn. Severed limbs regrow after 2 mins."
  },
  {
    name: "Resurrection",
    class: "Bard, Cleric",
    level: "7",
    school: "Necromancy",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Return dead creature (within 100 years) to life with full HP. Cures non-magical ailments."
  },
  {
    name: "Reverse Gravity",
    class: "Druid, Sorcerer, Wizard",
    level: "7",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "100 ft",
    components: "V, S, M",
    duration: "Conc. (1 min)",
    effect: "50 ft Radius, 100 ft High. DEX Save: Grab anchor or fall upward. Slam damage at top."
  },
  {
    name: "Sequester",
    class: "Wizard",
    level: "7",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S, M",
    duration: "Until Dispelled",
    effect: "Object/Creature becomes invisible and enters suspended animation. Cannot be located by divination."
  },
  {
    name: "Simulacrum",
    class: "Wizard",
    level: "7",
    school: "Illusion",
    castingTime: "12 Hours",
    range: "Touch",
    components: "V, S, M",
    duration: "Until Dispelled",
    effect: "Create snow duplicate of beast/humanoid. Has half HP and same stats/spells."
  },
  {
    name: "Symbol",
    class: "Bard, Cleric, Druid, Wizard",
    level: "7",
    school: "Abjuration",
    castingTime: "1 Minute",
    range: "Touch",
    components: "V, S, M",
    duration: "Until Dispelled",
    effect: "Inscribe glyph with trigger. Effect: Death, Discord, Fear, Hopelessness, Insanity, Pain, Sleep, or Stun."
  },
  {
    name: "Teleport",
    class: "Bard, Sorcerer, Wizard",
    level: "7",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "10 ft",
    components: "V",
    duration: "Instant",
    effect: "Instantly transport self and 8 creatures. Accuracy depends on familiarity (can fail/mishap)."
  },
  {
    name: "Whirlwind",
    class: "Druid, Sorcerer, Wizard",
    level: "7",
    school: "Evocation",
    castingTime: "1 Action",
    range: "300 ft",
    components: "V, M",
    duration: "Conc. (1 min)",
    effect: "10 ft radius, 30 ft high whirlwind. DEX Save: 10d6 bludgeoning damage + Restrained/Flung."
  },
  // ==========================
  //       LEVEL 8
  // ==========================
  {
    name: "Antimagic Field",
    class: "Cleric, Wizard",
    level: "8",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self (10 ft radius)",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "10 ft Sphere. Spells fail, magic items become mundane, summoned creatures vanish."
  },
  {
    name: "Antipathy/Sympathy",
    class: "Druid, Wizard",
    level: "8",
    school: "Enchantment",
    castingTime: "1 Hour",
    range: "60 ft",
    components: "V, S, M",
    duration: "10 Days",
    effect: "Ward object/area. Specified creatures are either attracted to or repelled by it (WIS Save)."
  },
  {
    name: "Clone",
    class: "Wizard",
    level: "8",
    school: "Necromancy",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Grow inert duplicate of creature. If original dies, soul transfers to clone."
  },
  {
    name: "Control Weather",
    class: "Cleric, Druid, Wizard",
    level: "8",
    school: "Transmutation",
    castingTime: "10 Minutes",
    range: "Self (5 miles)",
    components: "V, S, M",
    duration: "Conc. (8 Hours)",
    effect: "Change precipitation, temperature, and wind within 5 miles."
  },
  {
    name: "Demiplane",
    class: "Warlock, Wizard",
    level: "8",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "S",
    duration: "1 Hour",
    effect: "Open door to empty 30ft room or an existing demiplane you know."
  },
  {
    name: "Dominate Monster",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "8",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Conc. (1 Hour)",
    effect: "WIS Save: Telepathically control any creature. Takes total control action."
  },
  {
    name: "Earthquake",
    class: "Cleric, Druid, Sorcerer",
    level: "8",
    school: "Evocation",
    castingTime: "1 Action",
    range: "500 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "100 ft Radius. Ground shakes. DEX Save to avoid falling prone/into fissures. Structures collapse."
  },
  {
    name: "Feeblemind",
    class: "Bard, Druid, Warlock, Wizard",
    level: "8",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "INT Save: Target takes 4d6 psychic dmg. INT/CHA become 1. Cannot cast spells/speak. Remake save every 30 days."
  },
  {
    name: "Glibness",
    class: "Bard, Warlock",
    level: "8",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Self",
    components: "V",
    duration: "1 Hour",
    effect: "Replace any Charisma check roll with a 15. Magic cannot detect your lies."
  },
  {
    name: "Holy Aura",
    class: "Cleric",
    level: "8",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Allies gain Adv on saves. Enemies have Disadv on attacks. Fiends/Undead blinded on hit (CON Save)."
  },
  {
    name: "Incendiary Cloud",
    class: "Sorcerer, Wizard",
    level: "8",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S",
    duration: "Conc. (1 Minute)",
    effect: "20 ft Radius cloud. Moves 10 ft/turn. DEX Save: Take 10d8 fire damage."
  },
  {
    name: "Maze",
    class: "Wizard",
    level: "8",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Conc. (10 min)",
    effect: "Banish target to labyrinth demiplane. No save. INT Check (DC 20) to escape."
  },
  {
    name: "Mind Blank",
    class: "Bard, Wizard",
    level: "8",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: "V, S",
    duration: "24 Hours",
    effect: "Target immune to psychic damage, mind reading, charm, and divination sensors."
  },
  {
    name: "Power Word Stun",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "8",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V",
    duration: "Instant",
    effect: "Target with <150 HP is stunned. CON Save at end of turns to end effect."
  },
  {
    name: "Sunburst",
    class: "Druid, Sorcerer, Wizard",
    level: "8",
    school: "Evocation",
    castingTime: "1 Action",
    range: "150 ft",
    components: "V, S, M",
    duration: "Instant",
    effect: "60 ft Radius. CON Save: Take 12d6 radiant damage + blinded. Undead/Oozes have Disadv."
  },
  {
    name: "Telepathy",
    class: "Wizard",
    level: "8",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Unlimited",
    components: "V, S, M",
    duration: "24 Hours",
    effect: "Create telepathic link with familiar creature anywhere on same plane."
  },
  {
    name: "Tsunami",
    class: "Druid",
    level: "8",
    school: "Conjuration",
    castingTime: "1 Minute",
    range: "Sight",
    components: "V, S",
    duration: "Conc. (6 Rounds)",
    effect: "Create massive wall of water (300 ft long). STR Save: Take 6d10 bludgeoning + swept away."
  },

  // ==========================
  //       LEVEL 9
  // ==========================
  {
    name: "Astral Projection",
    class: "Cleric, Warlock, Wizard",
    level: "9",
    school: "Necromancy",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Special",
    effect: "Project spirit bodies into Astral Plane. Physical bodies remain in stasis."
  },
  {
    name: "Foresight",
    class: "Bard, Druid, Warlock, Wizard",
    level: "9",
    school: "Divination",
    castingTime: "1 Minute",
    range: "Touch",
    components: "V, S, M",
    duration: "8 Hours",
    effect: "Target cannot be surprised. Advantage on attacks, ability checks, and saves. Attackers have Disadv."
  },
  {
    name: "Gate",
    class: "Cleric, Sorcerer, Wizard",
    level: "9",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S, M",
    duration: "Conc. (1 Minute)",
    effect: "Create portal to another plane. Can pull specific named creature to you."
  },
  {
    name: "Imprisonment",
    class: "Warlock, Wizard",
    level: "9",
    school: "Abjuration",
    castingTime: "1 Minute",
    range: "30 ft",
    components: "V, S, M",
    duration: "Until Dispelled",
    effect: "WIS Save: Trap creature forever (Burial, Chaining, Hedge Prison, Minimus Containment, or Slumber)."
  },
  {
    name: "Mass Heal",
    class: "Cleric",
    level: "9",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "Instant",
    effect: "Heal 700 HP divided among any number of creatures. Cures blindness, deafness, diseases."
  },
  {
    name: "Meteor Swarm",
    class: "Sorcerer, Wizard",
    level: "9",
    school: "Evocation",
    castingTime: "1 Action",
    range: "1 Mile",
    components: "V, S",
    duration: "Instant",
    effect: "Four 40 ft Radius spheres. DEX Save: Take 20d6 fire + 20d6 bludgeoning damage (half on success)."
  },
  {
    name: "Power Word Kill",
    class: "Bard, Sorcerer, Warlock, Wizard",
    level: "9",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V",
    duration: "Instant",
    effect: "Target with <100 HP dies instantly. No save."
  },
  {
    name: "Prismatic Wall",
    class: "Wizard",
    level: "9",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "60 ft",
    components: "V, S",
    duration: "10 Minutes",
    effect: "Create multicolor wall. 7 layers of damage/effects (Fire, Acid, Lightning, Poison, Petrify, Restrain, Blind). Blocks spells."
  },
  {
    name: "Shapechange",
    class: "Druid, Wizard",
    level: "9",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Self",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "Transform into any creature (CR <= Level). Retain INT/WIS/CHA. Can change form each turn."
  },
  {
    name: "Storm of Vengeance",
    class: "Druid",
    level: "9",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Sight",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "360 ft Radius storm. Effects change each turn: Thunder, Acid Rain, Lightning, Hail, Freezing."
  },
  {
    name: "Time Stop",
    class: "Sorcerer, Wizard",
    level: "9",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "Self",
    components: "V",
    duration: "Instant",
    effect: "Take 1d4 + 1 extra turns in a row. Ends if you attack or affect another creature."
  },
  {
    name: "True Polymorph",
    class: "Bard, Warlock, Wizard",
    level: "9",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 ft",
    components: "V, S, M",
    duration: "Conc. (1 Hour)",
    effect: "WIS Save: Turn Creature to Creature, Creature to Object, or Object to Creature. Permanent if held for full duration."
  },
  {
    name: "True Resurrection",
    class: "Cleric, Druid",
    level: "9",
    school: "Necromancy",
    castingTime: "1 Hour",
    range: "Touch",
    components: "V, S, M",
    duration: "Instant",
    effect: "Return dead creature (within 200 years) to life with full HP. Can create new body if needed."
  },
  {
    name: "Weird",
    class: "Wizard",
    level: "9",
    school: "Illusion",
    castingTime: "1 Action",
    range: "120 ft",
    components: "V, S",
    duration: "Conc. (1 min)",
    effect: "30 ft Radius. WIS Save: Creatures Frightened. Take 4d10 psychic dmg each turn."
  },
  {
    name: "Wish",
    class: "Sorcerer, Wizard",
    level: "9",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Self",
    components: "V",
    duration: "Instant",
    effect: "Duplicate any spell of Level 8 or lower without components. Or alter reality (risky)."
  }
];